# Generated by Django 2.2.6 on 2022-06-13 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_slug', models.CharField(max_length=2500)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('job_type', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('posted_on', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('descriptors', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(related_name='job_postings', to='JPM.Technology')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
