# Generated by Django 2.2.6 on 2022-06-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='uid_slug',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='descriptors',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_on',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
