# Generated by Django 2.2.6 on 2022-06-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0002_auto_20220613_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
