# Generated by Django 2.2.6 on 2022-06-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0003_jobpost_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=255)),
                ('filter_url', models.URLField()),
                ('days', models.CharField(choices=[('1', 'Last 1 Day'), ('2', 'Last 3 Days')], default='1', max_length=255)),
            ],
        ),
    ]
