# Generated by Django 2.2.6 on 2022-06-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0004_hlf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlf',
            name='filter_url',
            field=models.CharField(max_length=1000),
        ),
    ]
