# Generated by Django 2.2.6 on 2022-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0005_auto_20220615_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='qualification',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
