# Generated by Django 2.2.6 on 2022-06-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0006_jobpost_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DePrioritized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('p', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
            ],
        ),
    ]
