# Generated by Django 2.2.6 on 2022-06-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0007_deprioritized'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DePrioritized',
            new_name='GStack',
        ),
    ]
