# Generated by Django 2.2.6 on 2022-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0009_jobpost_cp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ('-cp',)},
        ),
        migrations.AlterField(
            model_name='gstack',
            name='p',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='cp',
            field=models.FloatField(default=0.0),
        ),
    ]
