# Generated by Django 2.2.6 on 2022-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0010_auto_20220620_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackBall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ('cp',)},
        ),
    ]
