# Generated by Django 2.2.6 on 2022-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0011_auto_20220627_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='bgc',
            field=models.BooleanField(default=False),
        ),
    ]
