# Generated by Django 2.2.6 on 2022-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0012_jobpost_bgc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackball',
            name='title',
            field=models.BooleanField(default=False),
        ),
    ]
