# Generated by Django 2.2.6 on 2022-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0014_blackball_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='same_state',
            field=models.BooleanField(default=False),
        ),
    ]
