# Generated by Django 2.2.6 on 2022-06-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0016_jobpost_garbage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackball',
            name='tech',
            field=models.BooleanField(default=True),
        ),
    ]
