# Generated by Django 2.2.6 on 2022-07-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JPM', '0017_blackball_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
